# Star field at 350, -20


##################### Star catalogue parameters
centre_ra : 350
centre_dec : -22

# How wide we want to make the catalogue
# This is half the side of the square- so the code will select stars between (centre - this value) and (centre + this value)
star_catalogue_width_ra : 1
star_catalogue_width_dec : 1

final_star_catalogue_name_stem : "Panstarrs_match_Gaia_350_m20"

# Date for Observations
# This is for the proper motion correction
# Should be a string which astropy can parse
date_for_observations : "2021-07-10"

##################### Mosaic parameters
individual_image_glob : "/Volumes/OtherFiles/Science/Panstarrs_Mosaic/350_m22/*.fits"
final_image_filename : "Mosaics/Panstarrs_Mosiac_350_m20.fits"
image_resolution_arcsec : 1.5


##################### Profound Parameters
#profound_mask_name : "/Volumes/OtherFiles/Science/Panstarrs_Mosaic/SkyMasks/Mosaic/segmap_StarField_350_-22.fits"
profound_mask_name : "SkyMasks/Mosaic/segmap_StarField_350_-22.fits"
profound_catalogue_name : "ProfoundCatalogues/profound_catalogue_350_-22.csv"
profound_zero_mag : 24.76

##################### Tiling

SourceCat : "350_m20_comissioning"

final_catalogue_name : "~/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/StarCatalogues/equally_spaced_350_m22.csv"
guide_star_filename: "~/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/StarCatalogues/Panstarrs_match_Gaia_350_m20_guides.csv"
standard_star_filename: "~/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/StarCatalogues/Panstarrs_match_Gaia_350_m20_standards.csv"

# Stem to attach to all the tile files we'll make. Will have an underscore after it
output_filename_stem: "350_m20_comissioning"

# Where to collect all the output files. In here, we'll make folders called 'Configuration', 'Plots', 'Tiles' and 'Logs'
# This folder is made if it doesn't exist
output_folder: "TilingOutputs/350_m20_equally_spaced"

# Parameters used in the code
fresh_start : False
MAX_TRIES: 999
configure_field : True

tiling_type : greedy
allocation_type : random
proximity : 220 # This is  14.5*15.008
Nsel : 19
N_targets_per_Hector_field : 19
Nsel_guides : 100
Nsel_standards : 100

TwoDF_FOV_radius : 1.0
exclusion_zone : 220  # This is 14.5mm in arcseconds: 14.5 * 15.008
Hector_FOV_outer_radius : 0.9318
Hector_FOV_inner_radius : 0.0

fraction_to_reobserve : 0.0

#Do we want to use the 'hybrid' approach to rescale the proximity value if the configuration code is struggling?
Rescale_proximity: True

fill_spares_with_repeats: True

columns_for_target_tile_saving : ['ID', 'RA', 'DEC', 'g_mag', 'r_mag', 'i_mag', 'z_mag', 'y_mag', 'GAIA_g_mag', 'GAIA_bp_mag', 'GAIA_rp_mag', 'pmRA', 'pmDEC', 'Re', 'GAL_MU_E_R', 'Mstar']

columns_for_guide_tile_saving : ['ID', 'RA', 'DEC', 'r_mag', 'type', 'pmRA', 'pmDEC']


