# Star field at 310, -22

filename : "config/Field_310_m22.yaml"
FIELD : "310_m22"
##################### Star catalogue parameters
centre_ra : 308.789015591 # This won't be exactly 310 due to the way the Panstarrs skycells are laid out. See note below in the Mosaic Download section
centre_dec : -22.200

# How wide we want to make the catalogue
# This is half the side of the square- so the code will select stars between (centre - this value) and (centre + this value)
star_catalogue_width_ra : 1
star_catalogue_width_dec : 1

final_star_catalogue_name_stem : "Panstarrs_match_Gaia_310_m22"

# Date for Observations
# This is for the proper motion correction
# Should be a string which astropy can parse
date_for_observations : "2022-06-26 14:00"

target_output_name : "results/StarCatalogues/Panstarrs_match_Gaia_310_m22_targets.csv"
guide_star_filename: "results/StarCatalogues/Panstarrs_match_Gaia_310_m22_guides.csv"
standard_star_filename: "results/StarCatalogues/Panstarrs_match_Gaia_310_m22_standards.csv"

##################### Mosaic download
# Use https://ps1images.stsci.edu/cgi-bin/ps1filenames.py?ra=ZZZ&dec=-22 to find closest skycell
# Then check the exact centre of this skycell (e.g. go to https://ps1images.stsci.edu/cgi-bin/ps1filenames.py?skycell=ZZZ.44)! 
# Otherwise the skymasks tend to not cover some of the sky fibres
# Each skycell is a 10x10 grid, with number 000 being the bottom left, 010 just above it, 001 to its right, etc
# 44 is the centre (since it's 0 based indexing)
# See https://outerspace.stsci.edu/display/PANSTARRS/PS1+Sky+tessellation+patterns 
# and https://outerspace.stsci.edu/display/PANSTARRS/PS1+Image+Cutout+Service#PS1ImageCutoutService-Scriptedimagedownloadsandimagecutoutextractions
download_files : True
skycell : '0868'


##################### Mosaic parameters
individual_image_glob : "/Volumes/OtherFiles/Science/Panstarrs_Mosaic/310_m22/*.fits"
final_image_filename : "results/Mosaics/Panstarrs_Mosiac_310_m22.fits"
image_resolution_arcsec : 1.5


##################### Profound Parameters
profound_mask_name : "results/SkyMasks/Mosaic/segmap_StarField_310_-22.fits"
profound_catalogue_name : "results/ProfoundCatalogues/profound_catalogue_310_-22.csv"
profound_zero_mag : 24.76

##################### Tiling

starfield_type : "entire_catalogue"

SourceCat : "310_m22_comissioning"

final_catalogue_name : "results/StarCatalogues/310_m22.csv"

# Stem to attach to all the tile files we'll make. Will have an underscore after it
output_filename_stem: "310_m22"

# Where to collect all the output files. In here, we'll make folders called 'Configuration', 'Plots', 'Tiles' and 'Logs'
# This folder is made if it doesn't exist
output_folder: "results/TilingOutputs/310_m22"

# Parameters used in the code
fresh_start : True
MAX_TRIES: 999
configure_field : True

tiling_type : greedy
allocation_type : random
proximity : 220 # This is  14.5*15.008
Nsel : 19
N_targets_per_Hector_field : 19
Nsel_guides : 100
Nsel_standards : 100

TwoDF_FOV_radius : 1.0
exclusion_zone : 220  # This is 14.5mm in arcseconds: 14.5 * 15.008
Hector_FOV_outer_radius : 0.92 #0.9318
Hector_FOV_inner_radius : 0.0

fraction_to_reobserve : 0.0

#Do we want to use the 'hybrid' approach to rescale the proximity value if the configuration code is struggling?
Rescale_proximity: True

fill_spares_with_repeats: True

columns_for_target_tile_saving : ['ID', 'RA', 'DEC', 'g_mag', 'r_mag', 'i_mag', 'z_mag', 'y_mag', 'GAIA_g_mag', 
'GAIA_bp_mag', 'GAIA_rp_mag', 'Mstar', 'Re', 'z', 'GAL_MU_E_R', 'pmRA', 'pmDEC']

columns_for_guide_tile_saving : ['ID', 'RA', 'DEC', 'r_mag', 'type', 'pmRA', 'pmDEC']


